<a href="https://colab.research.google.com/github/OshankAgrawal/Foundation-of-Data-Science/blob/main/NUMPY_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise

**Question 01:- Write a numpy program to get Numpy version.**

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


**Question 02:- Write a NumPy program to test whether none of the
elements of a given array are zero.**

Test Case of all()

In [1]:
import numpy as np
df=np.array([[True,True,True,True],[False,True,False,True],[True,True,True,True],[False,True,False,True]])
all=np.all(df, axis=-1)
print(df)
print()
print(all)

[[ True  True  True  True]
 [False  True False  True]
 [ True  True  True  True]
 [False  True False  True]]

[ True False  True False]


Test Case of any()

In [2]:
import numpy as np
df=np.array([[True,True,True,True],[False,False,False,False],[True,True,True,True],[False,True,False,True]])
all=np.any(df, axis=-1)
print(df)
print()
print(all)

[[ True  True  True  True]
 [False False False False]
 [ True  True  True  True]
 [False  True False  True]]

[ True False  True  True]


Answer

**Method 1**

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50,0,56,0,23])
print(arr)
print("If zero is present inside the array than 'False' is return otherwise 'True'")
print()
print(np.all(arr))

[10 20 30 40 50  0 56  0 23]
If zero is present inside the array than 'False' is return otherwise 'True'

False


About **np.all()**

Reference Link: https://numpy.org/doc/stable/reference/generated/numpy.all.html

axis=0 means vertical checking

axis=1 means horizontal checking

in 2 dimensional array

all() is used to check all the elements

**Method 2**

In [4]:
import numpy as np
arr = np.array([[10,20,30,1],[70,80,90,0]])
print(arr)
print()
print(np.any((arr == 0),axis=0))

[[10 20 30  1]
 [70 80 90  0]]

[False False False  True]


About **np.any()**

Reference Link: https://numpy.org/doc/stable/reference/generated/numpy.any.html

Axis alignment is same as all()

any() is used to check a special number

**Question 03:- Write a NumPy program to create an element-wise
comparison (greater, greater_equal, less and less_equal) of
two given arrays.**

In [5]:
import numpy as np

i = np.array([1,2,3,4,5])
j = np.array([6,7,8,9,10])

print("Original arrays")

print(i)
print(j,"\n")

print("Greater")
print(np.greater(i,j),"\n")

print("Greater and Equal")
print(np.greater_equal(i,j),"\n")

print("Less")
print(np.less(i,j),"\n")

print("Less and Equal")
print(np.less_equal(i,j))


Original arrays
[1 2 3 4 5]
[ 6  7  8  9 10] 

Greater
[False False False False False] 

Greater and Equal
[False False False False False] 

Less
[ True  True  True  True  True] 

Less and Equal
[ True  True  True  True  True]


**Question 04:- Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.**

In [6]:
import numpy as np
arr = np.array([1,7,13,105])
print("Our array is ",arr)
print("Size of memory occupied by the said array: ",(arr.size*arr.itemsize),"bytes")

Our array is  [  1   7  13 105]
Size of memory occupied by the said array:  32 bytes


**Question 05:- Write a NumPy program to create an array of integers
from 30 to 70.**

Answer

In [7]:
import numpy as np
arr = np.arange(30,71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


About **np.arange()**

Reference Link: https://numpy.org/doc/stable/reference/generated/numpy.arange.html

There are three mazor attribute of this function

1- Start (optional Default value is 0)

2- Stop (mandatory)

3- Step (optional Default value is 1)

Return the Integers from start (inclusive) to stop (exclusive) with the interval equals to step.

**Question 06:- Write a NumPy program to create an array of all even
integers from 30 to 70.**

Answer

In [8]:
import numpy as np
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Question 07:- Write a NumPy program to create a 3x3 identity matrix.**

Answer

**Method 01**

In [9]:
import numpy as np
matrix = np.arange(10,19).reshape((3, 3))
print(matrix)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


About **np.reshape()**

Reference Link: https://numpy.org/doc/stable/reference/generated/numpy.reshape.html

This function is used to reshape the array

**Method 02**

In [10]:
import numpy as np
elements = np.arange(123,132)
print(elements)
print()
matrix = np.reshape(elements,(3,3))
print(matrix)

[123 124 125 126 127 128 129 130 131]

[[123 124 125]
 [126 127 128]
 [129 130 131]]


**Method 03**

In [11]:
import numpy as np
elements = np.random.randint(100,200,9)
print(elements)
print()
matrix = np.reshape(elements,(3,3))
print(matrix)

[155 158 168 107 149 145 130 192 181]

[[155 158 168]
 [107 149 145]
 [130 192 181]]


About           **np.random.randint()**

Reference Link: https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html

there are two major ttributes

1- Low

2- High

Return random integers from low (inclusive) to high (exclusive).

**Method 04**

In [12]:
import numpy as np
matrix = np.random.randint(1,size=(3,3))
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Iteration on matrix

In [13]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array: ")
print(a)
print(":Each element of the array is: ")
for x in np.nditer(a):
  print(x,end=" ")

Original array: 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
:Each element of the array is: 
10 11 12 13 14 15 16 17 18 19 20 21 

In [14]:
import numpy as np
print(np.random.randint(10,size=(3,3,3,3)))

[[[[4 3 1]
   [5 0 4]
   [0 0 7]]

  [[4 8 4]
   [4 4 6]
   [2 3 1]]

  [[3 1 9]
   [5 0 5]
   [6 4 6]]]


 [[[2 7 8]
   [0 8 7]
   [7 1 6]]

  [[1 6 7]
   [1 0 7]
   [3 6 0]]

  [[2 1 5]
   [8 5 8]
   [2 5 2]]]


 [[[7 4 6]
   [9 2 4]
   [0 0 0]]

  [[9 0 8]
   [0 9 0]
   [5 8 8]]

  [[5 5 1]
   [3 1 5]
   [6 6 9]]]]
